import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full antialiased">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var savedColor = localStorage.getItem('accent-color');
                if (savedColor) {
                  var root = document.documentElement;
                  root.style.setProperty('--primary', savedColor);
                  root.style.setProperty('--ring', savedColor);
                  root.style.setProperty('--sidebar-primary', savedColor);
                  root.style.setProperty('--sidebar-ring', savedColor);
                  root.style.setProperty('--primary-foreground', '#ffffff');
                }
              } catch (e) {}
            `,
          }}
        />
      </head>
      <body style={{ fontFamily: "var(--font-sans), sans-serif" }} className={`${inter.variable} min-h-full flex flex-col font-sans bg-background text-foreground`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
